// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<SpeedController> RobotMap::driveTrain1LeftBack;
std::shared_ptr<SpeedController> RobotMap::driveTrain1LeftFront;
std::shared_ptr<SpeedController> RobotMap::driveTrain1rightback;
std::shared_ptr<SpeedController> RobotMap::driveTrain1rightfront;
std::shared_ptr<RobotDrive> RobotMap::driveTrain1RobotDrive41;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    LiveWindow *lw = LiveWindow::GetInstance();

    driveTrain1LeftBack.reset(new TalonSRX(0));
    lw->AddActuator("DriveTrain1", "Left Back", std::static_pointer_cast<TalonSRX>(driveTrain1LeftBack));
    
    driveTrain1LeftFront.reset(new TalonSRX(1));
    lw->AddActuator("DriveTrain1", "Left Front", std::static_pointer_cast<TalonSRX>(driveTrain1LeftFront));
    
    driveTrain1rightback.reset(new TalonSRX(2));
    lw->AddActuator("DriveTrain1", "right back", std::static_pointer_cast<TalonSRX>(driveTrain1rightback));
    
    driveTrain1rightfront.reset(new TalonSRX(3));
    lw->AddActuator("DriveTrain1", "right front", std::static_pointer_cast<TalonSRX>(driveTrain1rightfront));
    
    driveTrain1RobotDrive41.reset(new RobotDrive(driveTrain1LeftFront, driveTrain1LeftBack,
              driveTrain1rightfront, driveTrain1rightback));
    
    driveTrain1RobotDrive41->SetSafetyEnabled(true);
        driveTrain1RobotDrive41->SetExpiration(0.1);
        driveTrain1RobotDrive41->SetSensitivity(0.5);
        driveTrain1RobotDrive41->SetMaxOutput(1.0);


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
